project:
  type: website

website:
  page-navigation: true
  title: "Data Science in a Box"
  description: "Data Science in a Box contains the materials required to teach (or learn from) the course described above, all of which are freely-available and open-source."


  navbar:
    background: "#A7D5E8"
    align: center
    title: false
    collapse-below: lg
 
    left:
      - text: "Overview"
        href: index.qmd
      - text: "IGH"
        href: IGH.qmd
        
  sidebar:
      
      - id: Overview
        title: "Overview"


            
      - id: IGH
        title: "IGH"
        contents:
          - href: IGH.qmd
          - genotype.qmd
          - novel_allele.qmd
          - challenging_ASCs.qmd
          - problems.qmd
          - section: "IGHV1"
            contents:
            - href: IGHV4-EITI.qmd
          - section: "IGHV4"
            contents:
            - IGHV1-ISRF.qmd

format:
  html:
    theme: [Journal]
    css: [style.css, index.css]
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Atkinson Hyperlegible"
    grid:
      sidebar-width: 250px
      body-width: 1000px
      margin-width: 300px

freeze: auto

editor: visual